### ISSUE TITLE
Explicit delete feature of RisingDragon::Event

### ISSUE THREAD

**Issue by ToruIwashita** [ota42y/rising_dragon#14]
For example, at exception handling, I want to delete `RisingDragon::Event` at an arbitrary timing. 

Simply implement it as follows.

e.g.)

```
    1 module RisingDragon
    2   class Event
    3     attr_reader :id, :type, :timestamp, :data
~   4     def initialize(id:, type:, timestamp:, data:, sqs_msg:)
    5       @id = id
    6       @type = type
    7       @timestamp = timestamp
    8       @data = data
+   9       @sqs_msg = sqs_msg
   10     end
   11
   12     def to_json(*option)
   13       {
   14         id: @id,
   15         type: @type,
   16         timestamp: @timestamp,
   17         data: @data,
   18       }.to_json(*option)
   19     end
+  20
+  21     def delete
+  22       @sqs_msg.delete
+  23     end
   24   end
   25 end
```

This is an implementation to have sqs_msg passed from `Shoryuken` as an attribute of `RisingDragon::Event`.

Delete of `RisingDragon::Event` can be realized with this implementation, but I do not know whether it meets the designing policy of RisingDragon (it will increase the responsibility of `RisingDragon::Event`), I would like you to check it.

**Comment by ota42y** [comment]
done
